// 🎯 AMAZING Collection Types - Auto-generated
// Do not edit this file manually - it will be overwritten
// Generated by: scripts/generate-collection-types.ts
// Generated at: 2025-09-01T04:08:33.089Z

// Base types
export interface BaseCollection {
  id: string
  createdAt: Date
  updatedAt: Date
}

export interface Media extends BaseCollection {
  filename: string
  mimeType: string
  filesize: number
  width?: number
  height?: number
  alt?: string
  caption?: string
}

// UNION TYPES
// ============

export type AllCollections = 'customers' | 'appointments' | 'services' | 'stylists' | 'inventory' | 'suppliers' | 'commissions' | 'service-packages' | 'wait-list' | 'documentation' | 'documentation-templates' | 'documentation-workflows' | 'notifications'
